"""
Apply material properties, boundary conditions, and pressure load to .inp file.
Called via: abaqus cae -noGUI apply_bc.py -- args.json result.json

args.json schema:
  {
    "inp_file": "/path/to/job.inp",
    "bc_params": {
      "material": {
        "name": "STEEL_A106_GrB",
        "youngs_modulus": 200000,
        "poissons_ratio": 0.3,
        "density": 7.85e-9,
        "allowable_stress": 138.0
      },
      "pressure_mpa": 10.0,
      "fixed_faces": "inlet",        # "inlet" | "outlet" | "both"
      "element_type": "C3D10"        # C3D4(Tet4) | C3D10(Tet10) | C3D8R(Hex8)
    },
    "work_dir": "/path/to/work",
    "job_name": "fea_bc"
  }

Strategy:
  - Read the .inp file generated by mesh_case1/2.py
  - Append material, section, BC, and load definitions
  - Write modified .inp to a new file (*_bc.inp)
  - Returns path to the modified .inp
"""
import sys
import os
import json

args_file   = sys.argv[-2]
result_file = sys.argv[-1]

with open(args_file) as f:
    args = json.load(f)

inp_file  = args["inp_file"]
bc_params = args.get("bc_params", {})
work_dir  = args.get("work_dir", os.path.dirname(inp_file))
job_name  = args.get("job_name", "fea_bc")

# ── Material defaults (ASME B31.3 carbon steel A106 Gr.B) ────────────────────
mat     = bc_params.get("material", {})
mat_name        = mat.get("name",            "STEEL_A106_GrB")
E               = float(mat.get("youngs_modulus",    200_000))   # MPa
nu              = float(mat.get("poissons_ratio",      0.3))
density         = float(mat.get("density",           7.85e-9))   # tonne/mm^3
allowable       = float(mat.get("allowable_stress",    138.0))   # MPa

pressure        = float(bc_params.get("pressure_mpa", 10.0))     # MPa
fixed_faces     = bc_params.get("fixed_faces", "inlet")          # "inlet"|"outlet"|"both"
elem_type       = bc_params.get("element_type", "C3D10")         # tet10 default

# ── Read existing .inp ────────────────────────────────────────────────────────
with open(inp_file) as f:
    inp_content = f.read()

# ── Build material + section block ───────────────────────────────────────────
material_block = f"""
**
** ============================================================
** MATERIAL PROPERTIES
** ============================================================
*Material, name={mat_name}
*Elastic
{E}, {nu}
*Density
{density},
**
** ============================================================
** SOLID SECTION (assign material to all elements)
** ============================================================
*Solid Section, elset=ELSET-ALL, material={mat_name}
,
**
** ============================================================
** ELEMENT SET (all elements)
** ============================================================
*Elset, elset=ELSET-ALL, generate
1, {_count_elements(inp_content)}, 1
"""

# ── Node sets for boundary conditions ────────────────────────────────────────
# We create node sets by picking nodes at extreme X positions
# (inlet = minimum X face, outlet = maximum X face)
# These will be refined on Abaqus PC after seeing the actual geometry.
bc_block = f"""
**
** ============================================================
** BOUNDARY CONDITIONS
** ============================================================
** Inlet face: fixed all DOF (encastre)
*Nset, nset=NSET-INLET, generate
1, 100, 1
** NOTE: Replace this placeholder with actual node set from mesh
**
*Boundary
NSET-INLET, ENCASTRE
"""

if fixed_faces == "both":
    bc_block += f"""
** Outlet face: also fixed
*Nset, nset=NSET-OUTLET, generate
101, 200, 1
** NOTE: Replace this placeholder with actual node set from mesh
*Boundary
NSET-OUTLET, 1, 3
"""

# ── Pressure load ─────────────────────────────────────────────────────────────
# Internal pressure applied on inner surface element faces
load_block = f"""
**
** ============================================================
** STEP: Static analysis
** ============================================================
*Step, name=Step-1, nlgeom=NO
*Static
1., 1., 1e-05, 1.
**
** Internal pressure load
** NOTE: SURF-INNER should be defined as inner surface element set
**       Replace with actual surface from mesh inspection
*Dsload
SURF-INNER, P, {pressure}
**
** ============================================================
** OUTPUT REQUESTS
** ============================================================
*Output, field, variable=PRESELECT
*Output, field
*Node Output
U, RF
*Element Output, directions=YES
S, E, MISES
*Output, history, variable=PRESELECT
*End Step
"""

# ── Assemble modified .inp ────────────────────────────────────────────────────
# Insert blocks before *End Assembly (or at end if not found)
insert_marker = "*End Assembly"
if insert_marker in inp_content:
    modified = inp_content.replace(
        insert_marker,
        insert_marker + "\n" + material_block
    )
else:
    modified = inp_content + "\n" + material_block

# Append BC and load
modified += bc_block + load_block

out_inp = os.path.join(work_dir, f"{job_name}_bc.inp")
with open(out_inp, "w") as f:
    f.write(modified)

# ── Result ────────────────────────────────────────────────────────────────────
result = {
    "status": "success",
    "modified_file": out_inp,
    "material": mat_name,
    "pressure_mpa": pressure,
    "note": (
        "Node sets NSET-INLET, NSET-OUTLET, and surface SURF-INNER are placeholders. "
        "Replace with actual sets from the mesh after Abaqus CAE inspection."
    ),
}

with open(result_file, "w") as f:
    json.dump(result, f, indent=2)


def _count_elements(inp_content: str) -> int:
    """Rough element count from .inp (used for ELSET-ALL generate line)."""
    count = 0
    in_elem = False
    for line in inp_content.split("\n"):
        l = line.strip()
        if l.upper().startswith("*ELEMENT"):
            in_elem = True
            continue
        if in_elem:
            if l.startswith("*"):
                in_elem = False
            elif l and not l.startswith("**"):
                count += 1
    return max(count, 1)
